import { UsageMetadata } from '../types';
import { CostCalculator } from './costCalculator';

export interface FalImageResult {
  url: string;
  width: number;
  height: number;
}

export interface FalGenerateResponse {
  images: FalImageResult[];
  seed?: number;
  has_nsfw_content?: boolean[];
}

export interface FalImageGenerationOptions {
  count?: number;
  imageSize?: 'square' | 'square_hd' | 'portrait_4_3' | 'portrait_16_9' | 'landscape_4_3' | 'landscape_16_9';
  enableSafetyChecker?: boolean;
}

export class FalImageService {
  private static readonly API_BASE = 'https://queue.fal.run';
  private static readonly MODEL_DEV = 'fal-ai/flux/dev';
  private static readonly MODEL_SCHNELL = 'fal-ai/flux/schnell';
  private static readonly TIMEOUT_MS = 120_000; // 2 minutes

  private static getApiKey(): string {
    const key = process.env.FAL_API_KEY;
    if (!key) throw new Error('FAL_API_KEY_MISSING');
    return key;
  }

  /**
   * Generate 2 images in parallel using fal.ai flux/dev with different seeds.
   * Falls back to flux/schnell on failure.
   * 
   * @param prompt - English image prompt (generated by AI)
   * @param options - Generation options
   * @returns Array of image URLs + usage metadata
   */
  static async generateImages(
    prompt: string,
    options: FalImageGenerationOptions = {}
  ): Promise<{ images: FalImageResult[]; usage: UsageMetadata }> {
    const { count = 2, imageSize = 'square_hd', enableSafetyChecker = true } = options;

    // Generate unique seeds for each image
    const seeds = Array.from({ length: count }, () => Math.floor(Math.random() * 2_147_483_647));

    try {
      const results = await Promise.all(
        seeds.map((seed) => this.generateSingle(prompt, seed, imageSize, enableSafetyChecker, this.MODEL_DEV))
      );

      const images = results
        .filter((r): r is FalGenerateResponse => r !== null)
        .flatMap((r) => r.images);

      const usage = CostCalculator.createFalImageUsageMetadata(images.length, 'flux-dev');

      if (images.length === 0) {
        throw new Error('No images generated');
      }

      return { images, usage };
    } catch (error) {
      console.warn('[FalImageService] flux/dev failed, falling back to flux/schnell:', error);

      // Fallback to schnell
      try {
        const results = await Promise.all(
          seeds.map((seed) => this.generateSingle(prompt, seed, imageSize, enableSafetyChecker, this.MODEL_SCHNELL))
        );

        const images = results
          .filter((r): r is FalGenerateResponse => r !== null)
          .flatMap((r) => r.images);

        const usage = CostCalculator.createFalImageUsageMetadata(images.length, 'flux-schnell');

        if (images.length === 0) {
          throw new Error('No images generated even with fallback');
        }

        return { images, usage };
      } catch (fallbackError) {
        console.error('[FalImageService] Both models failed:', fallbackError);
        throw fallbackError;
      }
    }
  }

  /**
   * Generate a single image via fal.ai REST API.
   */
  private static async generateSingle(
    prompt: string,
    seed: number,
    imageSize: string,
    enableSafetyChecker: boolean,
    model: string
  ): Promise<FalGenerateResponse | null> {
    const url = `${this.API_BASE}/${model}`;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.TIMEOUT_MS);

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Authorization': `Key ${this.getApiKey()}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt,
          seed,
          image_size: imageSize,
          enable_safety_checker: enableSafetyChecker,
          num_images: 1,
          sync_mode: true, // Wait for result synchronously
        }),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`fal.ai API error ${response.status}: ${errorText}`);
      }

      const data: FalGenerateResponse = await response.json();
      return data;
    } catch (error) {
      clearTimeout(timeoutId);
      if ((error as Error).name === 'AbortError') {
        console.error(`[FalImageService] Timeout generating with ${model}`);
      } else {
        console.error(`[FalImageService] Error generating with ${model}:`, error);
      }
      return null;
    }
  }

  /**
   * Download image from URL as Buffer for Firebase Storage upload.
   * Note: This should be called from server-side (Server Action or API route).
   */
  static async downloadImage(imageUrl: string): Promise<Buffer> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30_000);

    try {
      const response = await fetch(imageUrl, {
        signal: controller.signal,
      });
      clearTimeout(timeoutId);

      if (!response.ok) {
        throw new Error(`Failed to download image: ${response.status}`);
      }
      const arrayBuffer = await response.arrayBuffer();
      return Buffer.from(arrayBuffer);
    } catch (error) {
      clearTimeout(timeoutId);
      throw error;
    }
  }
}
