"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.publishDemoPost = exports.checkSubscriptionRenewals = void 0;
const functions = require("firebase-functions/v1");
const admin = require("firebase-admin");
admin.initializeApp();
// Export Schedulers
var subscription_scheduler_1 = require("./schedulers/subscription.scheduler");
Object.defineProperty(exports, "checkSubscriptionRenewals", { enumerable: true, get: function () { return subscription_scheduler_1.checkSubscriptionRenewals; } });
// Callable function to publish demo post to @AiKanalishe
exports.publishDemoPost = functions
    .region('europe-west1')
    .runWith({ secrets: ['TELEGRAM_BOT_TOKEN', 'TELEGRAM_DEMO_CHANNEL_ID'] })
    .https.onCall(async (data, context) => {
    var _a;
    // 1. Validation
    const { text, url } = data;
    if (!text || typeof text !== 'string') {
        throw new functions.https.HttpsError('invalid-argument', 'Text is required');
    }
    if (text.length > 4096) {
        throw new functions.https.HttpsError('invalid-argument', 'Text is too long');
    }
    // 2. Configuration - injected via Firebase Secret Manager
    const botToken = process.env.TELEGRAM_BOT_TOKEN;
    const channelId = process.env.TELEGRAM_DEMO_CHANNEL_ID || '@AiKanalishe';
    if (!botToken) {
        throw new functions.https.HttpsError('failed-precondition', 'Telegram Bot Token not configured');
    }
    // Clean up potential markdown codeblocks that the AI sometimes adds
    const cleanedText = text.replace(/```(?:html)?\n([\s\S]*?)```/g, '$1').trim();
    // 3. Construct Message
    const footer = `\n\n----\nGenerated by <a href="https://telegenie-studio.web.app/widget">TeleGenie Demo</a>\nSource: ${url || 'Unknown'}`;
    const fullMessage = cleanedText + footer;
    try {
        // 4. Send to Telegram
        const targetChatId = channelId.startsWith('@') || /^-?\d+$/.test(channelId)
            ? channelId
            : `@${channelId}`;
        console.log(`Publishing to Telegram. Bot: ${botToken.substring(0, 10)}..., Chat: ${targetChatId}`);
        const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                chat_id: targetChatId,
                text: fullMessage,
                parse_mode: 'HTML',
                disable_web_page_preview: true
            })
        });
        const result = (await response.json());
        if (!result.ok) {
            console.error('Telegram API Error:', result);
            throw new functions.https.HttpsError('internal', `Telegram API Error: ${result.description}`);
        }
        return { success: true, messageId: (_a = result.result) === null || _a === void 0 ? void 0 : _a.message_id, channelId };
    }
    catch (error) {
        console.error('Publishing failed:', error);
        throw new functions.https.HttpsError('internal', 'Failed to publish post');
    }
});
//# sourceMappingURL=index.js.map