"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.publishDemoPost = exports.checkSubscriptionRenewals = void 0;
const functions = require("firebase-functions/v1");
const admin = require("firebase-admin");
admin.initializeApp();
// Export Schedulers
var subscription_scheduler_1 = require("./schedulers/subscription.scheduler");
Object.defineProperty(exports, "checkSubscriptionRenewals", { enumerable: true, get: function () { return subscription_scheduler_1.checkSubscriptionRenewals; } });
// Callable function to publish demo post to @AiKanalishe
exports.publishDemoPost = functions.https.onCall(async (data, context) => {
    var _a, _b, _c;
    // 1. Validation
    const { text, url } = data;
    if (!text || typeof text !== 'string') {
        throw new functions.https.HttpsError('invalid-argument', 'Text is required');
    }
    if (text.length > 4096) { // Telegram limit
        throw new functions.https.HttpsError('invalid-argument', 'Text is too long');
    }
    // 2. Configuration
    const config = functions.config();
    const botToken = (_a = config.telegram) === null || _a === void 0 ? void 0 : _a.bot_token;
    const channelId = ((_b = config.telegram) === null || _b === void 0 ? void 0 : _b.demo_channel_id) || '@AiKanalishe';
    if (!botToken) {
        throw new functions.https.HttpsError('failed-precondition', 'Telegram Bot Token not configured');
    }
    // 3. Construct Message
    const footer = `\n\n----\nGenerated by [TeleGenie Demo](https://telegenie-studio.web.app/widget)\nSource: ${url || 'Unknown'}`;
    const fullMessage = text + footer;
    try {
        // 4. Send to Telegram
        // Ensure channelId starts with @ if it's a handle
        const targetChatId = channelId.startsWith('@') || /^-?\d+$/.test(channelId)
            ? channelId
            : `@${channelId}`;
        console.log(`Publishing to Telegram. Bot: ${botToken.substring(0, 10)}..., Chat: ${targetChatId}`);
        // Using built-in fetch (Node 18+)
        const response = await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                chat_id: targetChatId,
                text: fullMessage,
                parse_mode: 'HTML',
                disable_web_page_preview: true
            })
        });
        // Need to cast response.json() result
        const result = (await response.json());
        if (!result.ok) {
            console.error('Telegram API Error:', result);
            throw new functions.https.HttpsError('internal', `Telegram API Error: ${result.description}`);
        }
        return { success: true, messageId: (_c = result.result) === null || _c === void 0 ? void 0 : _c.message_id, channelId };
    }
    catch (error) {
        console.error('Publishing failed:', error);
        throw new functions.https.HttpsError('internal', 'Failed to publish post');
    }
});
//# sourceMappingURL=index.js.map